Kwest.UI.Web/Controllers/CollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

using Kwest.UI.Web.ExtensionMethods;
using Kwest.APIClient;
using Kwest.ViewModels;
using Kwest.ViewModels.Collection;
using Kwest.ViewModels.Payment;
using Kwest.UI.Web.ViewModel;
using Kwest.UI.Web.Attributes;

namespace Kwest.UI.Web.Controllers
{
    public class CollectionController : Controller
    {
        ICollectionClient collections;
        IPaymentClient payment;

        public CollectionController(ICollectionClient collections, IPaymentClient payment)
        {
            this.collections = collections;
            this.payment = payment;
        }

        #region index
        [AcceptVerbs("Get", "Post")]
        public async Task<ActionResult> Index(CollectionIndexViewModel model)
        {
            if (model.Criteria != null)
            {
                return View(new CollectionIndexViewModel()
                {
                    Collections = await this.collections.Get(model.Criteria),
                    Criteria = model.Criteria
                });
            }
            return View(new CollectionIndexViewModel() { Collections = await this.collections.Get() });
        }

        #endregion

        #region single
        [HttpGet]
        public async Task<ActionResult> Single(string collectionId, string orderId = null)
        {
            if (!String.IsNullOrEmpty(orderId))
            {
                await payment.CheckPaymentStatus(orderId);
                ViewBag.Message = "Done";
            }
            var collection = (await collections.Get(collectionId, this.Request.Cookies.User()?.Id));
            return View(collection);
        }

        [HttpPost]
        public async Task<ActionResult> Single(string collectionId, string collectionTitle, decimal donationValue)
        {
            var result = await payment.Pay(this.CreatePayment(collectionId, collectionTitle, donationValue, this.Request.Url.AbsoluteUri));
            if (result.Succeeded)
            {
                return Redirect(result.RedirectURL);
            }
            else
            {
                this.ModelState.AddModelError(String.Empty, "Couldn't connect with payment service. Try again later");
            }
            var collection = await collections.Get(collectionId, this.Request.Cookies.User()?.Id);
            return View(collection);
        }

        private PaymentViewModel CreatePayment(string collectionId, string collectionTitle, decimal donationValue, string baseContinueURL)
        {
            return new PaymentViewModel()
            {
                Amount = donationValue,
                CollectionID = collectionId,
                CollectionTitle = collectionTitle,
                BaseContinueURL = baseContinueURL,
                UserID = this.Request.Cookies.UserLoggedIn() ? this.Request.Cookies.User().Id : null
            };
        }
        #endregion

        #region create
        [HttpGet]
        [AuthGuard(Authorized = true, Redirect = true, RedirectUrl = "~/Account/Login")]
        public ActionResult Create() => View();

        [HttpPost]
        [AuthGuard(Authorized = true, Redirect = true, RedirectUrl = "~/Account/Login")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TemporaryCollectionFormDTO model)
        {
            this.ModelState.Clear();
            var response = await collections.Create(this.CreateCollectionViewModel(model));
            if (response is null)
            {
                return RedirectToAction("Index", "Home");
            }
            this.ModelState.AddModelErrors(response);
            return View(model);
        }

        private CollectionFormDTO CreateCollectionViewModel(TemporaryCollectionFormDTO model) =>
            new CollectionFormDTO()
            {
                Title = model.Title,
                MoneyNeeded = model.MoneyNeeded,
                Begins = model.Begins,
                Ends = model.Ends,
                MainImage = model.MainImage?.ToBinaryArray(),
                MainImageMime = model.MainImage?.ContentType,
                Description = model.Description,
                MainVideo = model.MainVideo?.ToBinaryArray(),
                MainVideoMime = model.MainVideo?.ContentType,
                CurrentUserId = this.Request.Cookies.UserLoggedIn() ? this.Request.Cookies.User().Id : null
            };
        #endregion

        #region pick
        [HttpPost]
        [AuthGuard(Authorized = true, Redirect = true, RedirectUrl = "~/Account/Login")]
        public async Task<ActionResult> Pick(string collectionId)
        {
            var response = await this.collections.Pick(collectionId, this.Request.Cookies.User().Id);
            if(response is null)
            {
                ViewBag.Message = "Collection has been picked succesfully";
            }
            else
            {
                // do it on feature/messaging branch
            }
            return RedirectToAction("Single", new { collectionId });
        }
        #endregion

        #region free-payment
        [HttpPost]
        [AuthGuard(Authorized = true, Redirect = true, RedirectUrl = "~/Account/Login")]
        public async Task<ActionResult> FreePayment(string collectionId)
        {
            await this.payment.FreePay(new PaymentViewModel()
            {
                CollectionID = collectionId,
                UserID = this.Request.Cookies.User().Id
            });
            ViewBag.Message = "Free payment used";
            return RedirectToAction("Single", new { collectionId });
        }
        #endregion
    }
}

Kwest.UI.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Threading.Tasks;

using Kwest.APIClient;

namespace Kwest.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        ICollectionClient collections;

        public HomeController(ICollectionClient collections)
        {
            this.collections = collections;
        }

        public async Task<ActionResult> Index()
        {
            return View(await collections.Picked());
        }
    }
}

Kwest.UI.Web/Views/Home/Index.cshtml
@model IEnumerable<Kwest.ViewModels.Collection.Icon.CollectionIconViewModel>
@{
    ViewBag.Title = "Home Page";
}

@if (Model != null && Model.Count() != 0)
{
    <div class="row">
        <div class="col-8 offset-2">
            <div class="collection-picked">

                <div id="picked-collections" class="carousel slide " data-ride="carousel">

                    @{ var firstCollection = Model.ElementAt(0); }
                    <div class="carousel-inner">

                        <div class="carousel-item active">
                            <a href="@Url.Action("Single", "Collection", new { collectionId = firstCollection.Id })">
                                <img class="d-block w-100" src="data:image/jpeg;base64, @Convert.ToBase64String(firstCollection.MainImage)" />
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>@firstCollection.Title</h5>
                                </div>
                            </a>
                        </div>

                        @foreach (var pickedCollection in Model.Skip(1))
                        {
                            <div class="carousel-item">
                                <a href="@Url.Action("Single", "Collection", new { collectionId = pickedCollection.Id })">
                                    <img class="d-block w-100" src="data:image/jpeg;base64, @Convert.ToBase64String(pickedCollection.MainImage)" />
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>@pickedCollection.Title</h5>
                                    </div>
                                </a>
                            </div>
                        }
                    </div>

                    <a class="carousel-control-prev" href="#picked-collections" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>

                    <a class="carousel-control-next" href="#picked-collections" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>

            </div>
        </div>
    </div>
}