Kwest.UI.Web/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

using Kwest.APIClient;
using Kwest.UI.Web.ExtensionMethods;
using Kwest.UI.Web.Attributes;

namespace Kwest.UI.Web.Controllers
{
    public class GameController : Controller
    {
        IGameClient game;

        public GameController(IGameClient game)
        {
            this.game = game;
        }

        [HttpGet]
        [AuthGuard(Authorized = true, Redirect = true, RedirectUrl = "~/Account/Login")]
        public async Task<ActionResult> Achievement() => View(await game.UserAchievements(Request.Cookies.User().Id));

        [HttpGet]
        public async Task<ActionResult> Ranking() => View(await game.UserRanking());
    }
}

Kwest.UI.Web/Views/Shared/_Layout.cshtml
@using Kwest.ViewModels.Login
@using Kwest.UI.Web.ExtensionMethods;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kwest - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand fixed-top shadow">
        <div class="container">
            <div class="navbar-nav">
                <span class="navbar-brand text-plaster">
                    Kwest
                </span>
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Collection", "Index", "Collection", null, new { @class = "nav-item nav-link" })
                @Html.ActionLink("Ranking", "Ranking", "Game", null, new { @class = "nav-item nav-link" })
            </div>
            <div class="d-flex flex-row-reverse">
                @if (this.Request.Cookies.UserLoggedIn())
                {
                    <span class="navbar-brand navbar-user">@this.Request.Cookies.User().Nickname</span>
                    @Html.ActionLink("Logout", "Logout", "Account", new { URL = Request.Url.AbsoluteUri }, new { @class = "nav-item nav-link" });
                    @Html.ActionLink("Achievements", "Achievement", "Game", null, new { @class = "nav-item nav-link" });
                }
                else
                {
                    @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-item nav-link" })
                    @Html.ActionLink("Register", "Register", "Account", null, new { @class = "nav-item nav-link" })
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <footer>
        <p>&copy; Copyright @DateTime.Now.Year - Kwest</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>